### PR TITLE
add traceTransaction / storageRangeAt

### PR DESCRIPTION
**Pull request by yann300**

### CODE REVIEW

**Comment by chriseth** [comment]
Were the endpoints updated in the meantime?

**Comment by yann300** [comment]
`traceTransaction` is ok.
not sure about `storageRangeAt` @gumb0 ?

**Comment by gumb0** [comment]
`storageRangeAt` currently takes 5 params, see https://github.com/ethereum/cpp-ethereum/pull/3488

**Comment by yann300** [comment]
ok that should be ok like that

**Pull request merged**
